//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bootcamp_OOP_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_Sell
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_M_Sell()
        {
            this.TB_T_Transactions = new HashSet<TB_T_Transactions>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_Transactions> TB_T_Transactions { get; set; }

        public static implicit operator TB_M_Sell(int v)
        {
            throw new NotImplementedException();
        }
    }
}
